name: Build and Test
run-name: Build and test
on: [push]
jobs:
  BuildInstallers:
    runs-on: win-build-amd64
    steps:
      - run: echo "Job has run"
      - name: Check out repository code
        uses: actions/checkout@v5
      - name: Remove user-config.jam
        run: Remove-Item -Path (Join-Path -Path $env:USERPROFILE -ChildPath "user-config.jam") -ErrorAction SilentlyContinue
      #TEMP- name: Remove build directory
      #TEMP  run: Remove-Item -Path "D:\RB" -Recurse -Force -ErrorAction SilentlyContinue
      #TEMP- run: python run.py
      - name: Versions Artifact
        uses: actions/upload-artifact@v4
        with: 
          name: build-versions
          path: D:/RB/DEPENDENCY_VERSIONS.txt
      - name: Build Logs Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-Logs
          path: D:/RB/boost*log.txt
      - name: Full Build
        uses: actions/upload-artifact@v4
        with: 
          name: full-build
          path: D:/RB/boost*msvc-all*.7z
      - name: Installers Build
        uses: actions/upload-artifact@v4
        with: 
          name: installers-build
          path: D:/RB/boost*.exe
