name: Build and Test
run-name: Build and test
on: [push]
jobs:
  BuildInstallers:
    runs-on: win-build-amd64
    steps:
      - run: echo "Job has run"
      - name: Check out repository code
        uses: actions/checkout@v5
      - name: Remove user-config.jam
        run: Remove-Item -Path (Join-Path -Path $env:USERPROFILE -ChildPath "user-config.jam") -ErrorAction SilentlyContinue
      - name: Remove build directory
        run: Remove-Item -Path "D:\RB" -Recurse -Force -ErrorAction SilentlyContinue
      - run: python run.py
